package idv.emp.model;
// Generated Nov 18, 2018 8:46:17 PM by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * YlRoleId generated by hbm2java
 */
@Embeddable
public class EmpId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int empNo;

	public EmpId() {
	}

	public EmpId(int empNo) {
		this.empNo = empNo;
	}

	@Column(name = "emp_no", nullable = false)
	public int getEmpNo() {
		return this.empNo;
	}

	public void setEmpNo(int empNo) {
		this.empNo = empNo;
	}

	

}
